### ISSUE TITLE
[RFC] Accordion and Group Field

### ISSUE THREAD

**Issue by matthias-own3d** [own3d/docs#5]
We want to introduce two new input fields: `Accordion` and `Group`

## Accordion
![Screenshot 2024-05-29 154217](https://github.com/own3d/docs/assets/97446195/1bbae899-33a6-4698-86dd-890e522dbb17)

The `Accordion` should have a title and 1-n fields and can be open/closed. The open-state should be remembered (comparable to the current accordions in the sidebar).
Fields can be (unless there are objections) all other form fields. I personally would not support nested accordions at this time. Technically possible, of course.

The config would look like this:

```yaml
- type: accordion
  id: my-accordion
  attributes:
    label: My Test Accordion
    initial-open: true | false
  fields:
    - type: boolean
      id: random
      attributes:
        label: Random
        description: This is a description
        value: true
    - type: input
      id: text
      attributes:
        label: Text
        description: This is a description
        value: Hello World
        type: text
      validations:
        required: true
    - ...
```

## Group

![image](https://github.com/own3d/docs/assets/97446195/3eb542d7-87d0-436b-8a47-40468a48cc77)

The `group` should contain a title and fields.
The configuration would be similar:

```yaml
- type: group
  id: my-group
  attributes:
    label: My Test Group
  fields:
    - type: boolean
      id: random
      attributes:
        label: Random
        description: This is a description
        value: true
    - type: input
      id: text
      attributes:
        label: Text
        description: This is a description
        value: Hello World
        type: text
      validations:
        required: true
    - ...
```

## Required changes
We currently assume in `AppSourceInputs.vue` that the update event is triggered by the currently rendered input.

In this case, the update event should also return the input.id in addition to the changed value.

```html
<Component
  :is="components[input.type]"
  v-if="isVisible(input)"
  :model-value="source.values[input.id]"
  :values="source.values"
  :input="input"
  @update:model-value="newValue => commit(input.id, newValue)"
/>
```

```javascript
@update:model-value="(newValue, id) => commit(id ?? input.id, newValue)"
```

## Why not use one form field for both?
That's a good question.
In my opinion, we are more flexible with two separate form fields.  Especially when it comes to nesting. Nested accordions probably behave differently from groups. 

Furthermore, the component becomes more difficult to maintain, as we need corresponding class bindings, logic and a different DOM for both types.

"Group" and "Accordion" are self-explanatory. 3rd party developers will probably find the form fields more easily in the documentation.

/cc @ghostzero @oliverkoehler @Vincent-76 @StefanEnsmann
